# session check
###
GET http://localhost:3000/

# check auth
###
GET http://localhost:3000/user/protected

# Signup
###
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "username": "toba",
    "password": "him", 
    "email": "roba.adnew@gmail.com"
}

# login
###
POST http://localhost:3000/user/login
Content-Type: application/json 

{
    "usernameOrEmail": "roba",
    "usernameOrEmail": "roba",
    "password": "him"
}

# logout
###
GET http://localhost:3000/user/logout