# Signup
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "username": "roba",
    "password": "him", 
    "email": "roba.adnew@gmail.com"
}

###
# Login
POST http://localhost:3000/user/login
Content-Type: application/json 

{
    "username": "roba",
    "password": "him"
}