# Signup
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "username": "roba",
    "password": "him", 
    "email": "roba.adnew@gmail.com"
}

###
# Login
POST http://localhost:3000/user/login
Content-Type: application/json 

{
    "username": "roba",
    "password": "him"
}

###
# Load blog posts for a reader
GET http://localhost:4000/posts

###
# Load blog posts for an author
GET https://blogish-backend.vercel.app/posts/author
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODViOGYwMDlhNDM2MmJmODNmNjI1ZCIsIm5hbWUiOiJ0b2JhIiwiYXV0aG9yIjp0cnVlLCJpYXQiOjE3MjE3NTA4MjUsImV4cCI6MTcyMTc1NDQyNX0.AO3338iU4zCKSQI0f7QNLQU5XNwbgx5ZLVVSqxcnIXo


###
# Write a blog post
POST http://localhost:4000/posts/author
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODViOGYwMDlhNDM2MmJmODNmNjI1ZCIsIm5hbWUiOiJ0b2JhIiwiYXV0aG9yIjp0cnVlLCJpYXQiOjE3MjE3NTA4MjUsImV4cCI6MTcyMTc1NDQyNX0.AO3338iU4zCKSQI0f7QNLQU5XNwbgx5ZLVVSqxcnIXo
Content-Type: application/json

{
    "user": "6685b8f009a4362bf83f625d",
    "title": "making sure blogish is as good as deblog, BUT in vercel",
    "content": "now we're on the second thing"
}

###
# Edit a blog post
PUT http://localhost:4000/posts/author/669fd8f1e46642abcf1aa29e/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODViOGYwMDlhNDM2MmJmODNmNjI1ZCIsIm5hbWUiOiJ0b2JhIiwiYXV0aG9yIjp0cnVlLCJpYXQiOjE3MjE3NTA4MjUsImV4cCI6MTcyMTc1NDQyNX0.AO3338iU4zCKSQI0f7QNLQU5XNwbgx5ZLVVSqxcnIXo
Content-Type: application/json

{
    "content": "now we're on the second thing...and making sure we use the vercel domain...just one more edit"
}
### 
# Get post comments

GET https://blogish-backend.vercel.app/posts/669fd8f1e46642abcf1aa29e/comments


###
# Write a comment
POST https://blogish-backend.vercel.app/posts/669fd8f1e46642abcf1aa29e/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODViOGYwMDlhNDM2MmJmODNmNjI1ZCIsIm5hbWUiOiJ0b2JhIiwiYXV0aG9yIjp0cnVlLCJpYXQiOjE3MjE3NTA4MjUsImV4cCI6MTcyMTc1NDQyNX0.AO3338iU4zCKSQI0f7QNLQU5XNwbgx5ZLVVSqxcnIXo
Content-Type: application/json

{
    "content": "ok, last comment...for now"
}

###
# Edit a comment
PUT https://blogish-backend.vercel.app/posts/66984695c4557744acbcb057/comments/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODViOGYwMDlhNDM2MmJmODNmNjI1ZCIsIm5hbWUiOiJ0b2JhIiwiYXV0aG9yIjp0cnVlLCJpYXQiOjE3MjE3NTA4MjUsImV4cCI6MTcyMTc1NDQyNX0.AO3338iU4zCKSQI0f7QNLQU5XNwbgx5ZLVVSqxcnIXo
Content-Type: application/json

{
    "commentId": "669fdd50f8654cb50191ff0d",
    "newContent": "ok, last comment...for now....aaand this is the last edit"
}


###
# Get a new access token
POST https://blogish-backend.vercel.app/user/refresh-token
Content-Type: application/json

{
     "user": {
        "_id": "6685b8f009a4362bf83f625d"
    }
}

### 
# Delete current refresh tokens
DELETE https://blogish-backend.vercel.app/user/logout
Content-Type: application/json

{
    "userId": "669fc4e18e6c7d971a3fc9e0"
}